### ISSUE TITLE
Cannot set as default

### ISSUE THREAD

**Issue by schaffkat** [ngreenan/p5imapp#4] opened 2021-04-19 03:13 UTC
Is there any way to set the apk file as a default with newer Samsung software?

**Comment by ngreenan** [comment] 2021-04-19 07:30
Duplicate of #2 and #3

The app won't work on Android 10 or newer as it wasn't designed for it, and I've not been working on it for some time now so there won't be any updates, sorry!

**Closed as completed by ngreenan** 2021-04-19 07:30 UTC
