### ISSUE TITLE
Button No Work

### ISSUE THREAD

**Issue by ShadowTheLight** [ngreenan/p5imapp#5] opened 2022-12-14 16:48 UTC
I installed the apk but when pressing the "Set as Default" button, nothing happens.

**Comment by ngreenan** [comment] 2022-12-14 18:27
Duplicate of #2, #3, #4

this will be because the app doesn't work on Android 10 or newer, which is basically any recent phone, without changes to allow it to be set as default. I'm not supporting the app anymore, so this won't be fixed - sorry!

**Closed as completed** 2022-12-14 18:27 UTC

**Comment by ShadowTheLight** [comment] 2022-12-15 09:29
> I installed the apk but when pressing the "Set as Default" button, nothing happens.

Thanks for the info, maybe I'll learn some coding

**Comment by qianchencc** [comment] 2023-10-03 08:25
i wonder if you get some measures to solve the problem of button?i got this apk which version in v1.0.in this version,receive informain is agreed.but the button under resist me to recall them.because the button cover the input filed.i attemp to set it as the default app.but i can't,maybe it can not set normally in Android 14.If you have any main threads?i really like it.
![Uploading Screenshot_2023-10-03-16-21-14-590_com.ngreenan.persona5imapp.jpg…]()
